name: UCL pipeline test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu:22.04

    steps:
    - name: check operating system
      run: cat /etc/os-release

    - name: checkout repo
      uses: actions/checkout@v3

    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: deps
      run: pip install -r requirements.txt

    - name: run the tests
      run: pytest src.py

    - name: format check
      run: black --check src.py
